### ISSUE TITLE
Manifest merge failure

### ISSUE THREAD

**Issue by Kostyshina** [checkout/frames-android#1]
I'm getting build fail when added your library to dependencies:
> Error:../app/src/debug/AndroidManifest.xml:33:9-36 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:33:9-36
	is also present at [com.github.checkout:frames-android:v2.0.5] AndroidManifest.xml:14:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:6:5-10:19 to override.
../app/src/debug/AndroidManifest.xml:38:9-48 Error:
	Attribute application@roundIcon ...
	Attribute application@theme ...
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed with multiple errors, see logs

And then if I add `replace` build is failing again because some my style attributes are missing:
`error: failed linking references
attr/button not found`
 I'm not sure how can I fix it. Like I see you have `targetVersion` 27 and in our project it's 28, so maybe reason in it

**Comment by Kostyshina** [comment]
Okey, I see that you are using `<item name="button">#4050b5</item>` in your `AppTheme`

**Comment by ioan-ghisoi-cko** [comment]
@Kostyshina  can you check if the latest update is fixing your issue? (2.0.6)

**Comment by Kostyshina** [comment]
Thanks, now it's okay )
Also it will be good if you wrap `Volley` responses by your custom one, so then there will be no need to add this library to dependencies
