### ISSUE TITLE
Allow more customisation: set multiple font

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#129]
**Is your feature request related to a problem? Please describe.**
I need the pay button to have a custom font (also for the title of top bar)

**Describe the solution you'd like**
In the custom theme or programmatically

**Comment by patrick-hoban-cko** [comment]
Hey @benju69, thanks for raising this! 

Good news - we're working hard on making our UI _way more_ customisable through a component-based design (using Jetpack Compose). Watch this space as they'll be coming soon! I've also reached out to the LALALAB team directly about this (will tell them you asked too 👍 )

**Comment by benju69** [comment]
Now possible:
`val customFont = Font.Custom(R.font.font)

font = customFont`
