### ISSUE TITLE
Update website documentation

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#173]
**Is your feature request related to a problem? Please describe.**
With new version 4.0.0, documentation of https://www.checkout.com/docs/integrate/sdks/android-sdk is out of date

**Describe the solution you'd like**
Update the documentation, provide a guide how to do the upgrade/migration (like what is inside README)

**Comment by patrick-hoban-cko** [comment]
Hey @benju69 thanks for raising this! Our docs are being updated tomorrow (21/12) - there's just a slight overlap with the new SDK release and the new docs release.

Thanks for your feedback

**Comment by maxim-nosov-cko** [comment]
Hey @benju69 

The documentation is updated.
https://www.checkout.com/docs/integrate/sdks/android-sdk
