### ISSUE TITLE
Incompatible with stable compose material 3 version

### ISSUE THREAD

**Issue by Stuart-campbell** [checkout/frames-android#174]
**Describe the bug**

When using the latest version of material3
    ```implementation 'androidx.compose.material3:material3:1.0.1'```

App crashes opening form

```
 java.lang.NoSuchMethodError: No static method IconButton(Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;ZLandroidx/compose/foundation/interaction/MutableInteractionSource;Landroidx/compose/material3/IconButtonColors;Lkotlin/jvm/functions/Function2;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/IconButtonKt; or its super classes (declaration of 'androidx.compose.material3.IconButtonKt' appears in
```

**To Reproduce**
1. Create an empty project with latest m3 compose version
2. Launch form
3. Observe crash

**Expected behavior**
Should support a stable m3 version not an alpha

**Comment by maxim-nosov-cko** [comment]
Hi @Stuart-campbell 

We know about the issue and working on it.

**Comment by maxim-nosov-cko** [comment]
Improved in 4.0.1.
