### ISSUE TITLE
[V4.0.0] How would you support dark mode?

### ISSUE THREAD

**Issue by Stuart-campbell** [checkout/frames-android#177]
Question ->

```
!!! Any customisation needs to be done before creating Payment form mediator. Once mediator is created, any changes done on style will not be reflected in the UI !!!
```

Given this statement how would you update the colors when the user switches to darkmode?

**Comment by patrick-hoban-cko** [comment]
Hey @Stuart-campbell 

We don't have specific support for 'darkmode', i.e. for when a user switches to that - but we can consider adding this feature in the future.

I'd recommend taking a look at our 'Theme UI' in our Sample App if you want to see how we've created a darkmode themed payment page, if this is the sort of experience you're looking to create for your customers :)

**Comment by Stuart-campbell** [comment]
Thanks for the quick replay, yeah my concern is the user changing the theme while the screen is presented. Not a massive issue admittedly but would be great to support in the future. I shall close the ticket as this answers my question. Thanks
