### ISSUE TITLE
[4.0.0] How we can add views on top of form?

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#180]
**Is your feature request related to a problem? Please describe.**
Hello I want to display a progress bar, and a snackbar on top of checkout form
I don't see how is possible in my activity

**Describe the solution you'd like**
Expose a view/composable from PaymentFormMediator or with styles

**Comment by maxim-nosov-cko** [comment]
Hi @benju69 

Please take a look at our[ java app sample](https://github.com/checkout/frames-android/tree/master/app) it should give you an idea of how it can be achieved.
Overall there are a few ways either use an activity/fragment's root view (if you need a compose container view just get it from the view graph) or create a transparent activity or fragment and show it on the top.

**Comment by benju69** [comment]
Ok, got it, thank you :)
