### ISSUE TITLE
[4.0.0] Web View of 3DS

### ISSUE THREAD

**Issue by Devs-97Eats** [checkout/frames-android#187]
Hi all,

I don't understand how webView **container** works, please check below code: 

```
container = this.findViewById(android.R.id.content),

ThreeDSRequest threeDSRequest = new ThreeDSRequest(
                this.findViewById(android.R.id.content),
                redirectUrl,
                Constants.SUCCESS_URL,
                Constants.FAILURE_URL,
                threeDSResultHandler
        );
```

Can you explain how it works. I tried to add webView for activity and fragment but it didn't work

**Comment by maxim-nosov-cko** [comment]
Hi @Devs-97Eats 

The container serves as a parent ViewGroup for 3DS. Any ViewGroup can be used for it.
F.e. in your case `this.findViewById(android.R.id.content)` root view group for particular activity is used as a container for 3DS WebView.

Please take a look at our [code sample](https://github.com/checkout/frames-android/blob/master/app/src/main/java/checkout/checkout_android/DemoActivity.java#:~:text=private%20void%20start3DS,%7D).
[Documentation](https://www.checkout.com/docs/integrate/sdks/android-sdk#Handle_3D_Secure:~:text=across%20the%20forms.-,Handle%203D%20Secure,-When%20you%20send).
