### ISSUE TITLE
How to change position of compoments?

### ISSUE THREAD

**Issue by alexviet** [checkout/frames-android#193]
Hi, i want to custom UI like this. Is it possible or not?
Everybody can help me? I don't know how to change position of components.

![Screen Shot 2023-02-17 at 10 44 07](https://user-images.githubusercontent.com/70317810/219544041-32eedaa3-082a-49d4-b549-a5238c96880d.png)

**Comment by patrick-hoban-cko** [comment]
Hi Alex, thanks for raising this. 

We don't currently support the feature described above, but we do have our prebuilt UI that you can use as an out-the-box solution. However, we do want to support this and will look to it as a future feature. 

Best,

Patrick
