### ISSUE TITLE
Handle platforms payment more easily + Add Debit direct for Germany

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#196]
**Is your feature request related to a problem? Please describe.**
Yes
Actually when paying with external payment methods (Ideal, Giropay, Sofort, BanContact, Paypal also), it's the app to handle this and not checkout, we open a webview and let the user fill in his info
But sometimes, we can't open a webview, the link is a deeplink to an app

Also Germans don't want to pay with a credit cards...
How we can add a SEPA Direct debit transaction from their bank? https://en.wikipedia.org/wiki/Direct_debit

**Describe the solution you'd like**
It will be nice the sdk handle this, even for Paypal, it will be better to open the app (if installed) instead of opening a webview

**Comment by patrick-hoban-cko** [comment]
Hey @benju69, we do want to add alternative payment methods such as SEPA in the future, but this is a larger piece of work.

Rough timelines would be towards the end of 2023 - stay tuned...

**Comment by patrick-hoban-cko** [comment]
Hey @benju69, we'll be looking to support alternative payment methods like SEPA in 2024, but will close this ticket for now in anticipation of that. 

Would be keen to get your thoughts on this closer to the time, so will message you and take this conversation offline!

Best,

Patrick
