### ISSUE TITLE
With an expired expiration date, an error message si displayed for less than a second

### ISSUE THREAD

**Issue by crewstyle** [checkout/frames-android#201]
**Describe the bug**
When you choose a debit/credit card with an expired expiration date, the SDK displays an error message for less than a second before removing it. In most of cases, the user won't see the error.

**To Reproduce**
1. Open a payment form
2. Use a card with an expired expiration date
3. See error appears and disappears quickly

**Expected behavior**
We need to let the error displayed for the user to see what's wrong

Thanks a lot

**Comment by crewstyle** [comment]
Hi @patrick-hoban-cko ,
We're using the 4.0.1 version

**Comment by patrick-hoban-cko** [comment]
Hey @crewstyle, we have recreated this issue and will fix it when we make our next larger release. 

I don't have any timelines right now, but I will update you with an ETA once I do.

Best,

Patrick

**Comment by crewstyle** [comment]
Thanks a lot @patrick-hoban-cko :)
During a meeting with your teammates, they told us the same good news 👍 

Best,
Achraf

**Comment by patrick-hoban-cko** [comment]
Hey @crewstyle, thank you for your patience on this! This has now been fixed in the latest release (4.1.0, https://github.com/checkout/frames-android/releases/tag/4.1.0). Please check there and if the issue still occurs, feel free to raise another query with us :)
