### ISSUE TITLE
Support the ability to pre-fill or inject fields

### ISSUE THREAD

**Issue by rodrigojmlourenco** [checkout/frames-android#202]
Hi everyone,

This request has been mentioned in two previous tickets and is a feature currently supported in the iOS SDK.

- [Issue 175](https://github.com/checkout/frames-android/issues/175)
- [Issue 191](https://github.com/checkout/frames-android/issues/191)

We would like to request the ability to pre-fill or inject specific fields, particularly the billing address. This is a feature you plan to reintroduce, mentioned [here](https://github.com/checkout/frames-android/issues/191#issuecomment-1413383794):

>  Injecting pre-filled data into the billing address and cardholder name fields was a feature we dropped to make a faster 4.0.0 release, but we would include this feature in a future release (no timelines at the moment though unfortunately).

We would like to understand what is the priority/timelines.

All the best

**Comment by patrick-hoban-cko** [comment]
Hey @rodrigojmlourenco, thanks for raising this! 

We will take this feature into account for our next larger release, as it's definitely something we'd like to add, but I don't have any timelines right now.

Once I have more info, I'll keep you updated.

Best,

Patrick

**Comment by patrick-hoban-cko** [comment]
Hey @rodrigojmlourenco, thank you for your patience on this!

We have now released this in a new update, 4.1.0, which you can find here: https://github.com/checkout/frames-android/issues/194.

Please check that release, and if you find any other issues, please do raise another query with us.
