### ISSUE TITLE
[UX] Pay Button of form should be enabled when input is filled correctly

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#203]
**Describe the bug**
Pay button should be enabled when I fill all the form without needing to press enter/close keyboard, OR should be enabled all the time and when I click it, input fields should show error or validation

**To Reproduce**
1. Go to form
2. Click on Pay button, can't
3. Fill all the fields, finish with security code
4. See pay button doesn't activate immediately when filling the last field, I need to tap to close the keyboard or click enter in keyboard

in my app: 
https://user-images.githubusercontent.com/2486590/235619363-0485c315-6f0b-4969-8fcc-59c9bf176a03.mp4

**Comment by deepesh-vasthimal-cko** [comment]
Hi @benju69 Thanks for reporting this issue. We are already aware of this and we plan to fix this in upcoming releases.
