### ISSUE TITLE
Error while migrating to v4.1.0

### ISSUE THREAD

**Issue by ankitcan** [checkout/frames-android#233]
Currently we’re using Checkout SDK version 3.1.2 in our source code and as per the [document ](https://github.com/checkout/frames-android#migrating) are suggesting to upgrade to new version 4.1.0

So while updating its throwing error. 

![checkout_android_sdk__4 1 0](https://github.com/checkout/frames-android/assets/85868391/d5329f06-386e-420b-9429-accfa4c0e800)

Currently we're using below dependency for dagger Hilt 

*Project Level Gradle*:  

`classpath 'com.google.dagger:hilt-android-gradle-plugin:2.28-alpha'`

*App Level Gradle :*

`//dagger
    implementation 'com.google.dagger:hilt-android:2.29.1-alpha'
    annotationProcessor 'com.google.dagger:hilt-android-compiler:2.29.1-alpha'

   //hilt-lifecycle
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02"
    annotationProcessor "androidx.hilt:hilt-compiler:1.0.0-alpha02"`

Kindly help us to resolve this issue ASAP.

**Comment by chintan-soni-cko** [comment]
Hi @ankitcan  could you try invalidating caches and restarting Android studio, and probably share your gradle files if it still persists? I tried to have the given dependencies in a sample Android app and it's able to build correctly.

**Comment by ankitcan** [comment]
Hi @chintan-soni-cko  Yes, I've tried all the possible solution (invalidating caches and restarting Android studio, Deleted Build folder) but its throwing error.

**Project level Gradle :**

`buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.6.1'
        classpath 'com.google.firebase:perf-plugin:1.4.0'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.28-alpha'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10'
        // in the individual module build.gradle files
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1' // Add this line
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`


**App Level Gradle** 

`plugins {
    id 'com.android.application'
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    id 'com.google.firebase.crashlytics'
    id 'com.google.firebase.firebase-perf'
    id 'dagger.hilt.android.plugin'
    id 'com.google.gms.google-services'
}

android {

  
    compileSdkVersion 33
    buildToolsVersion "33.0.1"
  
    defaultConfig {
        applicationId "com.package.name"
        minSdkVersion 22
        targetSdkVersion 33
        versionCode 1
        versionName "1"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }

    packagingOptions{
        exclude 'META-INF/rxjava.properties'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.navigation:navigation-fragment:2.3.3'
    implementation 'androidx.navigation:navigation-ui:2.3.3'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation 'com.google.android.gms:play-services-wallet:19.2.0'
    implementation 'com.google.dagger:hilt-android:2.29.1-alpha'
    annotationProcessor 'com.google.dagger:hilt-android-compiler:2.29.1-alpha'
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02"
    annotationProcessor "androidx.hilt:hilt-compiler:1.0.0-alpha02"
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.10.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    implementation 'com.onesignal:OneSignal:4.8.6'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.adjust.sdk:adjust-android:4.28.4'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.facebook.android:facebook-android-sdk:13.0.0'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.facebook.android:audience-network-sdk:6.5.1'
    implementation 'com.google.android.gms:play-services-auth:20.6.0'
    implementation 'com.google.android.gms:play-services-ads:22.1.0'
    implementation platform('com.google.firebase:firebase-bom:32.1.1')
    implementation 'com.google.firebase:firebase-dynamic-links'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-perf:20.3.3'
    implementation 'com.google.android.play:review:2.0.1'
    implementation 'com.airbnb.android:lottie:3.6.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.github.checkout:frames-android:4.1.0'
    implementation 'com.github.ome450901:SimpleRatingBar:1.5.1'
    implementation 'io.customer.android:tracking:3.3.2'
    implementation 'io.customer.android:messaging-push-fcm:3.3.2'
}`

**Comment by chintan-soni-cko** [comment]
Hi @ankitcan Thank you for providing the information. Please find below my comments:
1. From the Gradle file, it seems java based project, if yes Could you verify with the latest version `2.44` [reference](https://developer.android.com/training/dependency-injection/hilt-android#groovy)?
2. Additionally, please try to add plugin `id 'kotlin-kapt'` and kapt compiler dependency in the app level Gradle file. if it works for you.
3. Invalid caches and restart Android studio
From our side, I have tried Kotlin and Java project works fine, if performing the above steps will not work, it would be nice if you provide a demo project reproducing this issue. So, we can look into it.

**Comment by chintan-soni-cko** [comment]
@ankitcan Just following up on the issue. Are you still getting this issue?

**Comment by ankitcan** [comment]
@chintan-soni-cko I have to migrate to latest version [2.44](https://developer.android.com/training/dependency-injection/hilt-android#kts)
