### ISSUE TITLE
Hide Billing Address 

### ISSUE THREAD

**Issue by devs-gireeb** [checkout/frames-android#254]
**Is your feature request related to a problem? Please describe.**

I have encountered an issue with the instructions provided for handling the cardholder's name in the payment and billing forms. The current instructions focus on the cardHolderName and name fields but do not address the possibility of hiding or excluding the billing address. This is causing uncertainty in the implementation process.

**Describe the solution you'd like**

I would like clarification or additional instructions regarding the handling of the billing address. Specifically, if there is a need to hide or exclude the billing address in certain scenarios, it would be helpful to include explicit guidance in the provided documentation or instructions.

**Describe alternatives you've considered**

I have considered reaching out to support channels for clarification, but I believe that updating the documentation with clear instructions would benefit not only me but also other developers facing a similar issue.

**Additional context**

No additional context or screenshots at the moment.

**Comment by chintan-soni-cko** [comment]
@devs-gireeb Thank you for raising it. We will consider this improvement in documentation in future. From the description, I can understand the issue about how to handle the visibility of `billingForm`. Is it correct? if yes, you can do it by setting up `addressSummaryStyle` as null in `PaymentDetailsStyle`. Below is the code snippet for it. 
`PaymentFormStyle(PaymentDetailsStyle(addressSummaryStyle = null))`

Let us know, if more information required.

**Comment by devs-gireeb** [comment]
> @devs-gireeb Thank you for raising it. We will consider this improvement in documentation in future. From the description, I can understand the issue about how to handle the visibility of `billingForm`. Is it correct? if yes, you can do it by setting up `addressSummaryStyle` as null in `PaymentDetailsStyle`. Below is the code snippet for it. `PaymentFormStyle(PaymentDetailsStyle(addressSummaryStyle = null))`
> 
> Let us know, if more information required.

Hi @chintan-soni-cko,

Thank you for your prompt response and providing a solution. I implemented the suggested code snippet, and it worked perfectly for handling the visibility of the billing form. Your assistance is greatly appreciated!

If any further details or questions arise, I'll be sure to reach out.

Thanks again!
