### ISSUE TITLE
generate apk

### ISSUE THREAD

**Issue by MostafaSlaam** [checkout/frames-android#256]
when generate apk (debug or release)
AGPBI: {"kind":"error","text":"com.android.tools.r8.kotlin.H","sources":[{}],"tool":"D8"}

**Comment by deepesh-vasthimal-cko** [comment]
Hi @MostafaSlaam can you please give more detailed steps to reproduce the error ?

**Comment by chintan-soni-cko** [comment]
@MostafaSlaam
From the attached logs, it seems they may have an issue with the compatibility of kotlin and Gradle versions. I would encourage you to update all development environments to make the product compatible with the latest release 4.2.0. Additionally,  this is [release note](https://github.com/checkout/frames-android/releases/tag/4.2.0) from 4.2.0.
 If you still face the issue, it would be nice to receive gradle configuration details (for versions) to reproduce it from our side.
