### ISSUE TITLE
Getting "s" character in Checkout redirect page

### ISSUE THREAD

**Issue by DhineshKumarTel** [checkout/frames-android#261]
We are getting the "s" symbol on the redirect page when after verifying the 3DS 

**To Reproduce**
1. Open 3DS page
2. Verifiy 3DS credientials
3. Getting empty redirect page with "s" symbol on left corner

**Expected behavior**
The "s" symbol should not be in redirect page

**Screenshots**

**Comment by patrick-hoban-cko** [comment]
Hi @DhineshKumarTel, please could you tell us a bit more about the issue?

Which version of Frames Android are you seeing this issue occur on? Additionally, do you see this issue in the sample app, or only in your own application that is consuming the Frames Android SDK?

**Comment by patrick-hoban-cko** [comment]
Hi @DhineshKumarTel, I'm going to close this issue as it has been open some time. If you face any other issues, please open a separate ticket. 

Thanks!

Patrick
