### ISSUE TITLE
Customize style of the card component

### ISSUE THREAD

**Issue by iagormoraes** [checkout/frames-android#27]
Is there any way to manage the UI like styling the background of the toolbar and it's text color, and set the button to the bottom of the screen?

**Describe the solution you'd like**
A way to manage better the UI to not look like Material Design as not every interface follows it guidelines.

**Describe alternatives you've considered**
Allow style properties to manage better these elements on the UI.

**Additional context**
![Screen Shot 2019-12-16 at 18 14 50](https://user-images.githubusercontent.com/13892132/70928029-6b5d0a00-2030-11ea-83cd-d797ef3c4bcd.png)

**Comment by ioan-ghisoi-cko** [comment]
For now, you can customise with the theme property (https://github.com/checkout/frames-android#customisation-options). 

More customisation options will be added in a future major release. 

Keep in mind that the SDK can be used in a headless mode as well, and you can use your own UI.

**Comment by Ahmedc2l** [comment]
hey @ioan-ghisoi-cko may you clarify how could i use the SDK in a headless mode? and how could i change the "Card Details" title? Thanks.

**Comment by ioan-ghisoi-cko** [comment]
1) There is a section describing the flow for using your own custom payment form (headless mode) is in the README -> https://github.com/checkout/frames-android#for-using-the-module-without-the-ui-you-need-to-do-the-following (let me know if you need clarifications)

2) The language is picked up here (https://github.com/checkout/frames-android/tree/master/android-sdk/src/main/res). If you want to add a new language pack, let me know, or alternatively you can do a pull request if you are a native speaker in the language (that would help us a lot)

**Comment by maxim-nosov-cko** [comment]
The latest Frames SDK 4.0.0+ provides a wide range of customization, please take a look at it.
