### ISSUE TITLE
Billing Address Optional

### ISSUE THREAD

**Issue by muhammadimran021** [checkout/frames-android#274]
Dear Team Is there any option to make billing address optional ? or any option to hide billing address

**Comment by chintan-soni-cko** [comment]
Hi, @muhammadimran021 Thanks for raising it. Please find the existing conversation [here](https://github.com/checkout/frames-android/issues/254) to hide the billing address and to make it optional, you can add the below code in `PaymentFormConfig`:

```
style = PaymentFormStyle(
            PaymentDetailsStyle(
                addressSummaryStyle = DefaultAddressSummaryComponentStyle.light(
                    isOptional = true,
                ),
            ),
        )
```

**Comment by muhammadimran021** [comment]
Hi @chintan-soni-cko ,

Thank you for your support and providing a solution. I implemented the suggested solution, and it works 🎉🥳. 

Thanks!
