### ISSUE TITLE
Could not find com.fingerprint.android:pro:2.3.4.

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#277]
**Describe the bug**
Can't compile the project with last version 4.2.2, compiler could not resolve depenncies and not find com.fingerprint.android:pro:2.3.4.

**Comment by jheng-hao-lin-cko** [comment]
Hey thanks for raising it, does the project follow the setup guide [here](https://github.com/checkout/frames-android?tab=readme-ov-file#integration) by any chance?

**Comment by benju69** [comment]
Ok didn't see the new repository in readme, this should be mentionned in release notes

**Comment by jheng-hao-lin-cko** [comment]
No problem ;)
