### ISSUE TITLE
Manifest merger failed : Attribute application@theme value=(@style/Application.Theme) from AndroidManifest.xml

### ISSUE THREAD

**Issue by ashutoshdmi** [checkout/frames-android#31]
Manifest merger failed : Attribute application@theme value=(@style/Application.Theme) from AndroidManifest.xml:23:9-49
	is also present at [com.github.checkout:frames-android:v2.1.1] AndroidManifest.xml:19:9-40 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:17:5-202:19 to override.

i 'm not able to build the project.

**Comment by ioan-ghisoi-cko** [comment]
Updated in latest releases.

**Comment by charbgr** [comment]
@ioan-ghisoi-cko I am getting the same error with `3.1.0`. Adding `tools:replace="android:theme"` solves the issue but is this correct?
