### ISSUE TITLE
Missing proguard rules.

### ISSUE THREAD

**Issue by AEfremov** [checkout/frames-android#32]
Hello!

We had a problem in the project with Proguard rules and singing release apk. Button "PAY" in Payment form doesnt work and onError callback shows next error "Unexpected response code 422 for https://api.checkout.com/tokens". After minifyEnabled false a problem is gone.

Can you add rules for library in documentation.

Thanks for answer.

**Comment by nicolas-maalouf-cko** [comment]
Hi @AEfremov can you please try using the latest release? 
https://github.com/checkout/frames-android/releases/tag/v2.1.3

**Comment by davidvrgh** [comment]
Hello,
I am using dependency 'com.github.checkout:frames-android:v2.1.3', but still I am facing this issue.
When minifyEnabled is true onError(CardTokenisationFail error)  callback is executed with error.getRequestId(), error.getErrorType(), error.getErrorCodes() all returning null values.
Could you please comment on the status of this ticket.

**Comment by alex-chmyr-cko** [comment]
@davidvrgh can you please upgrade to either `v2.1.4` or `2.2.1` version. Be aware that the `2.2.1` has AndroidX support and you might need to do more changes in the app.

Thanks, 
Alex Chmyr

**Comment by davidvrgh** [comment]
> @davidvrgh can you please upgrade to either `v2.1.4` or `2.2.1` version. Be aware that the `2.2.1` has AndroidX support and you might need to do more changes in the app.
> 
> Thanks,
> Alex Chmyr

It worked.
Thanks Alex.
