### ISSUE TITLE
Override App icon

### ISSUE THREAD

**Issue by gongshoudao** [checkout/frames-android#33]
Your are SDK not APP. Don't place launcher icon in lib Okay?

**Comment by gongshoudao** [comment]
![image](https://user-images.githubusercontent.com/4568329/86563936-e4558c00-bf97-11ea-837a-37b4cfc5c6e1.png)

**Comment by kevin-jarvis-cko** [comment]
Thanks for your feedback! We're looking to remove unused resources (including appIcons) soon.

**Comment by ioan-ghisoi-cko** [comment]
Removed in latest releases.
