### ISSUE TITLE
Right to Left texts support

### ISSUE THREAD

**Issue by adas3000** [checkout/frames-android#36]
Is it possible to place text such as 'Card Number' in right side instead of left using PaymentForm ?

**Comment by ioan-ghisoi-cko** [comment]
Based on the language of the device the inputs accept RTL however, the label position is not customizable. You can, however, use the [headless mode](https://github.com/checkout/frames-android#for-using-the-module-without-the-ui-you-need-to-do-the-following), and use your own inputs, giving you full customisation options, and use the SDK to tokenise.
