### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by androideveloper** [checkout/frames-android#37]
Checkout Sdk still uses the old support library so it prevents us from disabling Jetifier which potentially increase compilation time required to process dependencies. Legacy support-library is not maintained anymore and essentially deprecated, the latest version is 28 (so no more support for newest API levels), no more bugfixes. Any plans on migrate to AndroidX?

**Comment by alex-chmyr-cko** [comment]
Hi @androideveloper, thank you for raising this. We're going to include this in the next release.

**Comment by androideveloper** [comment]
Nice! Thanks for keeping us posted

**Comment by alex-chmyr-cko** [comment]
@androideveloper we have released version 2.2.0 with AndroidX support.

**Comment by androideveloper** [comment]
@alex-chmyr-cko Thanks! 🎉
