### ISSUE TITLE
Remove launcher icons

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#39]
**Describe the bug**
My launcher icon is override by the one in the checkout sdk with a bugdroid

**To Reproduce**
Make a app with checkout, make a adaptive icon (ic_launcher.xml with foreground and background)

**Expected behavior**
The icon should not change

**Screenshots**
![image (19)](https://user-images.githubusercontent.com/2486590/96882568-be3cf480-147f-11eb-936b-e8f61f9566b3.png)

Expected: 
![Screenshot_1603375221](https://user-images.githubusercontent.com/2486590/96882597-c5fc9900-147f-11eb-82e9-9ae2f1f42a49.png)

**Smartphone (please complete the following information):**
any one

**Additional context**
Sdks should not contains android resources

**Comment by alex-chmyr-cko** [comment]
Hi @benju69, thank you for raising this. 
Can you please confirm the Frames Android version are you using? 

Thanks, 
Alex Chmyr

**Comment by benju69** [comment]
Hi I'm using the v2.1.4 version
Thanks

**Comment by alex-chmyr-cko** [comment]
Hi @benju69, we have released a new version of the Frames with AndroidX changes and I've included a fix for your issue. Please let us know if you would be able to update to 2.2.0 and confirm that it is working as expected? (mind that there's no "v" in "2.2.0" version name)

Thanks, 
Alex Chmyr

**Comment by benju69** [comment]
Yes it works thx

**Comment by alex-chmyr-cko** [comment]
@benju69 great! Closing this issue.
