### ISSUE TITLE
Cleanup the AndroidManifest application tag

### ISSUE THREAD

**Issue by awenger** [checkout/frames-android#42]
**Is your feature request related to a problem? Please describe.**
If you add the checkout sdk to a existing app it will not compile directly, you need to "tools:replace" some of the values in the AndroidManifest of the frames-android sdk to make it work.
In my opinion the library should not have any values defined here, as all of them will be overwritten by the app. It could even introduce problematic behavior, if it setups a behavior the developer does not expect. For example `supportsRtl` defaults to `false`. Adding the frames-android library to a android app that does not define this value by itself, it will change the support to true if the developer does not do anything against it. Not a normal behavior someone would expect by adding this library.

problematic part: https://github.com/checkout/frames-android/blob/e8a582cbf55a08b969f5ad793c5d37e25965218c/android-sdk/src/main/AndroidManifest.xml#L7-L13

**Describe the solution you'd like**
just `<application/>` should work just fine on first sight. It could be even possible to remove the `<application/>` tag altogether

**Describe alternatives you've considered**
using tools:replace to fix it

**Comment by shavinda-rabichandran-cko** [comment]
@awenger Thank you for reporting this issue.

A fix has been added in #44 included in release version **2.2.1**
