### ISSUE TITLE
Translations of texts

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#45]
**Is your feature request related to a problem? Please describe.**
The form is only in english

**Describe the solution you'd like**
Add Translations to new languages (using Google translate, translators or something else)
I can contribute to translate in french

**Comment by shavinda-rabichandran-cko** [comment]
Hi @benju69. Thank you for the request.

The main language supported by the payment form is English. We plan on adding new translations as and when they become available. 

However, the Payment Form can also be localised by including the translations in your `app` module for string resources in [string.xml](https://github.com/checkout/frames-android/blob/master/android-sdk/src/main/res/values/strings.xml).
