### ISSUE TITLE
Ignore javascript errors when handling 3DS1 challenge

### ISSUE THREAD

**Issue by shavinda-rabichandran-cko** [checkout/frames-android#51]
@shavinda-rabichandran-cko Also can you ignore the javascript errors while loading the success and failure urls in 3DS  method.  https://stackoverflow.com/questions/32530228/android-api-23-webview-how-to-ignore-javascript-errors

_Originally posted by @gstephin in https://github.com/checkout/frames-android/issues/49#issuecomment-779784386_

**Comment by shavinda-rabichandran-cko** [comment]
@gstephin Can you confirm If this is related to an error you have observed (in logcat) or if it is in reference to the lint warning produced when javascript is enabled?

**Comment by gstephin** [comment]
Logcat error -  "TypeError: Cannot read property 'getItem' of null
        at $stateProvider.state.controller

**Comment by shavinda-rabichandran-cko** [comment]
> Logcat error - "TypeError: Cannot read property 'getItem' of null
> at $stateProvider.state.controller

Can I please confirm whether this error prevents the user from completing the 3DS1 challenge flow?

If yes, can you provide some insight into how this can be reproduced?
 - Device type / API version
 - Scheme and Issuer (i.e. bank) of the test card used when this problem occurs.

**Comment by gstephin** [comment]
Its not preventing the completion 3DS1 Flow, this exception will arise if the success and failure webpages have some warnings(Causes a blank screen after entering the otp) . and these warnings can be ignored by enabling DomStorage settings in webview.
