### ISSUE TITLE
3DSecure webview is very small

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#61]
**Describe the bug**
3DS Webview is small it should take all the screen width and height I think

**To Reproduce**
1. Open payment form
2. Add a card
3. Use the handle3DS method on payment form
4. See the small Webview

**Expected behavior**
take all the screen width and height

**Comment by kevin-jarvis-cko** [comment]
Hi @benju69, thanks for taking the time to document this. Are you able to share a screenshot of the small webview, to make sure we're seeing what you're seeing?

**Comment by benju69** [comment]
![Screenshot_20210428_193553](https://user-images.githubusercontent.com/2486590/116854335-d4c6c400-abf7-11eb-96b5-27d8c0593269.png)

Hi yes I gave this screenshot for example

**Comment by kevin-jarvis-cko** [comment]
Hi @benju69 thanks for sharing the screenshot. In this case the webview is taking the full width of the screen, but the card issuer (Revolut here) has defined their page to display as shown. 

One point to note is that the 3DS WebView size is the same as the PaymentForm size. So theoretically if you were to add a big margin for the PaymentForm, then the WebView can be smaller. This is something that you can control.

Does that address this issue? Or are you still concerned that something isn't behaving correctly here?

**Comment by benju69** [comment]
Ok I understand now, it's good
