### ISSUE TITLE
Google Pay Token Generation fail

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#93]
**Describe the bug**
I'm trying to integrate and test Google Pay in my app
I'm passing the token to the API client
mCheckoutAPIClient!!.generateGooglePayToken(token!!.token)

But in the callback, the GooglePay Tokenisation fails I have an error in onError
errorType: request_invalid, errorCode: token_data_invalid

Do I forget something or I should activate something?

**Comment by maxim-nosov-cko** [comment]
Hi Benjamin.

Could you please provide more details, like device, Android API level, library version, and environment?

From the first look, it can be an issue with Google Pay Payload `token!!.token`.
Please make sure that it's not null.

If the old library version was used and it's possible to migrate to the newest `3.1.2` please try it as well.

**Comment by benju69** [comment]
Hey, sorry sure
I'm using the 3.1.1, in Sandbox environment, Real device with Android 11 (api30)
token is not null: ```
{
  "signature": "MEUCIQCOz6FjXjD7xSRiwy0cRGxVrCBmMfAFE5X6n/QdI2cDigIgHhbtEQIbkymE1xQK5oAdkwB+/XISJyLCa9zzf4MhFJA\u003d",
  "protocolVersion": "ECv1",
  "signedMessage": "{\"encryptedMessage\":\"z4V96mBjVjbumDSIwgc6NgvM1x7j2P0AJylz7RWMbUcEkkbJP3D9jEiJsOeifhX/xkIDOp0vKVFO6rFoctrwavXkb43++enu8r2Fck8iR9StPbtuAGv+CBDWanTGdb5vqnfx3tqGSxKFXB5eC8fi+TALxbkKlDPYLfEkvI+Xn1MT/gNKDmLb5aG0O1ahGQZFlcc0FmJwPSDORL0ftufSG4iNhgiUFpu5Yeicq87LrX88wcyCu3lYVka+PsVAMF9Z1yx9AWN2QLXQLGQ9WDoND7OyyeYsV8gpoYP1aAuRfMGRyFv6ZGpAPfGRKKfa+dzCC3AB6HGvHSe8VjWVYQneBJjrVK6heX6WeJMjodacQHsVC3kzY1zL97OpDw1+GoyYMHKWt9ySawmh/G7N42bWk0+KLWGn0+g7l6W0bRpTIAvJD4AgHcVLar9soD0c4XSfAUgsgwI3oJh7JFQT2yG/7txtFwi2IrSh/bEuMjPafeOZDAw2jMnMj3nrJ5e+Sh+efkVn8V3C6Kqf+42vgfIG0UDzyeorep1qqeujgqACOPjKLinvkgowJ8g4MY9SEYWReMHojOHOtuISw9ENSI1gqYKOeGQ\\u003d\",\"ephemeralPublicKey\":\"BI7BvCgESCoq1CcTFyKRjZ+Aka05Em63LrGZNw+Kew+BV1GjzVcULMjUZtGhZc2snB30A7CDVoXnMEXSe8gl2bM\\u003d\",\"tag\":\"qDrKqFUO0qMYU3CSpVDfxlrwTfn86zBRfkKfMHmis+k\\u003d\"}"
}
```
I will try with 3.1.2 version yes

**Comment by benju69** [comment]
Same error when using the 3.1.2 version
