### ISSUE TITLE
kotlin.Unit' was compiled in different version

### ISSUE THREAD

**Issue by dabitdev** [checkout/frames-android#95]
**Describe the bug**
While importent the project to a exiting app I am getting this issue:

```
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
```

I am using const val KOTLIN_VERSION = "1.4.31" in the main app

**Comment by maxim-nosov-cko** [comment]
Hi @dabitdev.

Increasing kotlin version is probably the fastest way to solve the issue.
Could you try to use `1.5.0`+ version?
